# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [main, check]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SHA_SHORT: ${GITHUB_SHA::7}
      RUNNER_NUMBER: ${GITHUB_RUN_NUMBER}
      VERSION_MAJOR: "0.9."
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
          prefix: ${GITHUB_REF_NAME}
          
      - name: Run show version
        run: echo "${{ env.VERSION_MAJOR }}$BUILD_NUMBER-${{ env.SHA_SHORT }}"
       
